version: '3.9'
services:
  influxdb:
    image: influxdb:2.1.1-alpine
    volumes:
      - influxdbv2:/var/lib/influxdb2
    ports:
      - "8086:8086"
    env_file:
      - ./.env
    entrypoint: ["./entrypoint.sh"]s

  grafana:
    image: grafana/grafana-enterprise:8.2.0
    ports:
      - 3000:3000
    user: '104'

volumes:
  influxdbv2:
